name: Lettisches Haus in Freiburg
favicon: null
layout_spectrum: 1
typography_spectrum: 0.276059343945235
title: Lettisches Haus in Freiburg
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74761537-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1ecfe'
    - '#87827e'
    - '#060702'
    - '#3e3623'
    - '#c6a700'
  brandStrength: 0.25
  lightness: 0.10518318554386497
  saturation: 0
  rhythmicContrast: 0.3801355343312025
purpose: []
